version: '2.2'

services:
    pwnable-xinetd:
        build: ./
        image: skyepodium/pwnable-xinetd
        # external:internal
        ports:
            - "60001:8080"
        expose:
            - "8080"
        pids_limit: 1024
        cpus: 0.5
        restart: unless-stopped
